openapi: 3.0.0
info:
  title: StudioV2 API
  version: 1.0.0
  description: StudioV2 REST API dokümantasyonu
paths:
  /api/auth/login:
    post:
      summary: Kullanıcı girişi
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Başarılı giriş
